import type { ConstructorCatalog } from '@/stores/constructor-store';

export function getMockIngredients(): ConstructorCatalog {
  return {
    bases: [
      {
        id: 'base-vanilla',
        name: 'Тёмный бисквит',
        description: 'Готовый тёмный полноразмерный ярус для квадратной формы',
        pricePerKg: 85000,
        visualKey: 'default',
        color: '#462F1E',
        available: true,
      },
      {
        id: 'base-chocolate',
        name: 'Шоколадный бисквит',
        description: 'Готовый шоколадный полноразмерный ярус',
        pricePerKg: 95000,
        visualKey: 'choco',
        color: '#3B260E',
        available: true,
      },
      {
        id: 'base-cream',
        name: 'Кремовый бисквит',
        description: 'Готовый кремовый полноразмерный ярус',
        pricePerKg: 92000,
        visualKey: 'cream',
        color: '#E7CEAB',
        available: true,
      },
      {
        id: 'base-glaze',
        name: 'Кремово-глазурный бисквит',
        description: 'Готовый кремово-глазурный полноразмерный ярус',
        pricePerKg: 98000,
        visualKey: 'glaze',
        color: '#E8C092',
        available: true,
      },
      {
        id: 'base-cherry',
        name: 'Вишнёвый бисквит',
        description: 'Готовый вишнёвый полноразмерный ярус',
        pricePerKg: 96000,
        visualKey: 'cherry',
        color: '#E7A8B4',
        available: true,
      },
      {
        id: 'base-pink',
        name: 'Розовый бисквит',
        description: 'Готовый розовый полноразмерный ярус',
        pricePerKg: 96000,
        visualKey: 'pink',
        color: '#FFABAE',
        available: true,
      },
    ],

    fillings: [
      {
        id: 'filling-strawberry',
        name: 'Клубничный крем',
        description: 'Нежный крем-чиз с пюре свежей клубники — лёгкий, слегка кисловатый, с ярким ягодным ароматом. Идеально сочетается с ванильным и лимонным бисквитом.',
        imageUrl: undefined,
        pricePerKg: 40000,
        visualKey: 'cream',
        available: true,
      },
      {
        id: 'filling-chocolate',
        name: 'Шоколадный ганаш',
        description: 'Шёлковый ганаш из тёмного бельгийского шоколада 70% с добавлением сливок. Насыщенный вкус какао без лишней сладости, тает во рту.',
        imageUrl: undefined,
        pricePerKg: 45000,
        visualKey: 'choco',
        available: true,
      },
      {
        id: 'filling-caramel',
        name: 'Солёная карамель',
        description: 'Домашняя варёная карамель с щепоткой морской соли — обволакивающий сладко-солёный вкус. Прекрасно дополняет шоколадный и банановый бисквит.',
        imageUrl: undefined,
        pricePerKg: 50000,
        visualKey: 'glaze-cream',
        available: true,
      },
    ],

    coatings: [
      {
        id: 'coating-cream',
        type: 'cream',
        name: 'Крем-чиз',
        pricePerKg: 20000,
        visualKey: 'cream',
        available: true,
      },
      {
        id: 'coating-cream-2',
        type: 'cream',
        name: 'Кремовая версия 2',
        pricePerKg: 20000,
        visualKey: 'cream-2',
        available: true,
      },
      {
        id: 'coating-milk',
        type: 'cream',
        name: 'Взбитые сливки',
        pricePerKg: 25000,
        visualKey: 'milk',
        available: true,
      },
      {
        id: 'coating-chocolate',
        type: 'cream',
        name: 'Шоколадный крем',
        pricePerKg: 30000,
        visualKey: 'choco',
        available: true,
      },
      {
        id: 'coating-chocolate-2',
        type: 'cream',
        name: 'Шоколадная версия 2',
        pricePerKg: 30000,
        visualKey: 'choco-2',
        available: true,
      },
      {
        id: 'coating-fondant',
        type: 'fondant',
        name: 'Мастика',
        pricePerKg: 35000,
        visualKey: 'pink',
        available: true,
      },
      {
        id: 'coating-fondant-2',
        type: 'fondant',
        name: 'Розовая версия 2',
        pricePerKg: 35000,
        visualKey: 'pink-2',
        available: true,
      },
      {
        id: 'coating-cream-glaze',
        type: 'cream',
        name: 'Кремовая глазурь',
        pricePerKg: 32000,
        visualKey: 'cream-glaze',
        available: true,
      },
    ],

    decorations: [
      {
        id: 'decor-berries',
        name: 'Ягодный декор',
        category: 'Ягоды',
        pricePerUnit: 6000,
        visualKey: 'blueberry',
        available: true,
      },
      {
        id: 'decor-chocolate-choco',
        name: 'Тёмный шоколад',
        category: 'Шоколад',
        pricePerUnit: 12000,
        visualKey: 'chocolate-choco',
        available: true,
      },
      {
        id: 'decor-chocolate-pink',
        name: 'Розовый шоколад',
        category: 'Шоколад',
        pricePerUnit: 15000,
        visualKey: 'chocolate-pink',
        available: true,
      },
      {
        id: 'decor-chocolate',
        name: 'Шоколадный декор',
        category: 'Шоколад',
        pricePerUnit: 12000,
        visualKey: 'chocolate',
        available: true,
      },
      {
        id: 'decor-cream',
        name: 'Кремовый декор',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'cream',
        available: true,
      },
      {
        id: 'decor-glaze-cream',
        name: 'Кремовая глазурь',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'glaze-cream',
        available: true,
      },
      {
        id: 'decor-glaze-cream-2',
        name: 'Кремовая глазурь 2',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'glaze-cream2',
        available: true,
      },
      {
        id: 'decor-glaze-choco',
        name: 'Шоколадная глазурь',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'glaze-choco',
        available: true,
      },
      {
        id: 'decor-glaze-pink',
        name: 'Розовая глазурь',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'glaze-pink',
        available: true,
      },
      {
        id: 'decor-meringue',
        name: 'Меренга',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'meringue',
        available: true,
      },
      {
        id: 'decor-top-cream',
        name: 'Крем сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-cream',
        available: true,
      },
      {
        id: 'decor-top-choco',
        name: 'Шоколад сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-choco',
        available: true,
      },
      {
        id: 'decor-top-pink',
        name: 'Розовый крем сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-pink',
        available: true,
      },
      {
        id: 'decor-top-meringue',
        name: 'Меренга сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-meringue',
        available: true,
      },
      {
        id: 'decor-top-glaze',
        name: 'Глазурь сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-glaze',
        available: true,
      },
      {
        id: 'decor-top-glaze-choco',
        name: 'Шоколадная глазурь сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-glaze-choco',
        available: true,
      },
      {
        id: 'decor-top-glaze-cream',
        name: 'Кремовая глазурь сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-glaze-cream',
        available: true,
      },
      {
        id: 'decor-top-glaze-cream-2',
        name: 'Кремовая глазурь сверху 2',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-glaze-cream2',
        available: true,
      },
      {
        id: 'decor-top-meringue-pink',
        name: 'Розовая меренга сверху',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'top-meringue-pink',
        available: true,
      },
      {
        id: 'decor-candle-gold',
        name: 'Свеча золотая',
        category: 'candle',
        pricePerUnit: 15000,
        visualKey: 'candle',
        available: true,
      },
      {
        id: 'decor-blueberry-one',
        name: 'Свеча по одному',
        category: 'candle',
        pricePerUnit: 12000,
        visualKey: 'blueberry-one',
        available: true,
      },
      {
        id: 'decor-glaze-one',
        name: 'Ягода по одному',
        category: 'Ягоды',
        pricePerUnit: 12000,
        visualKey: 'glaze-one',
        available: true,
      },
      {
        id: 'decor-chocolate-pink-one',
        name: 'Розовый шоколад по одному',
        category: 'Топперы',
        pricePerUnit: 12000,
        visualKey: 'chocolate-pink-one',
        available: true,
      },
      {
        id: 'decor-candle-one',
        name: 'Свеча по одному',
        category: 'candle',
        pricePerUnit: 12000,
        visualKey: 'candle-one',
        available: true,
      },
    ],

    shapes: [
      { id: 'circle', name: 'Круглый', surchargePercent: 0 },
      { id: 'square', name: 'Квадратный', surchargePercent: 10 },
      { id: 'heart', name: 'Сердце', surchargePercent: 15 },
    ],

    tierSurcharges: [
      { tierCount: 1, surcharge: 0 },
      { tierCount: 2, surcharge: 30000 },
      { tierCount: 3, surcharge: 60000 },
      { tierCount: 4, surcharge: 90000 },
    ],

    config: {
      maxDecorations: 40,
      maxInscriptionLength: 50,
      minWeightPerTier: 500,
      maxWeightPerTier: 5000,
      weightStep: 500,
    },
  };
}
