import type { ConstructorCatalog } from '@/stores/constructor-store';

export function getMockIngredients(): ConstructorCatalog {
  return {
    bases: [
      {
        id: 'base-vanilla',
        name: 'Ванильный бисквит',
        description: 'Классический нежный бисквит с ароматом ванили',
        pricePerKg: 80000,
        visualKey: 'default',
        color: '#FFF8E7',
        available: true,
      },
      {
        id: 'base-chocolate',
        name: 'Шоколадный бисквит',
        description: 'Насыщенный бисквит на бельгийском какао',
        pricePerKg: 90000,
        visualKey: 'choco',
        color: '#5C3D2E',
        available: true,
      },
      {
        id: 'base-red-velvet',
        name: 'Красный бархат',
        description: 'Бархатистый бисквит с характерным красным цветом',
        pricePerKg: 100000,
        visualKey: 'red',
        color: '#C0392B',
        available: true,
      },
    ],

    fillings: [
      {
        id: 'filling-strawberry',
        name: 'Клубничный крем',
        description: 'Нежный крем-чиз с пюре свежей клубники — лёгкий, слегка кисловатый, с ярким ягодным ароматом. Идеально сочетается с ванильным и лимонным бисквитом.',
        imageUrl: undefined,
        pricePerKg: 40000,
        visualKey: 'cream',
        available: true,
      },
      {
        id: 'filling-chocolate',
        name: 'Шоколадный ганаш',
        description: 'Шёлковый ганаш из тёмного бельгийского шоколада 70% с добавлением сливок. Насыщенный вкус какао без лишней сладости, тает во рту.',
        imageUrl: undefined,
        pricePerKg: 45000,
        visualKey: 'choco',
        available: true,
      },
      {
        id: 'filling-caramel',
        name: 'Солёная карамель',
        description: 'Домашняя варёная карамель с щепоткой морской соли — обволакивающий сладко-солёный вкус. Прекрасно дополняет шоколадный и банановый бисквит.',
        imageUrl: undefined,
        pricePerKg: 50000,
        visualKey: 'glaze-cream',
        available: true,
      },
    ],

    coatings: [
      {
        id: 'coating-cream',
        type: 'cream',
        name: 'Крем-чиз',
        pricePerKg: 20000,
        visualKey: 'cream',
        available: true,
      },
      {
        id: 'coating-fondant',
        type: 'fondant',
        name: 'Мастика',
        pricePerKg: 35000,
        visualKey: 'pink',
        available: true,
      },
    ],

    decorations: [
      {
        id: 'decor-strawberry',
        name: 'Клубника',
        category: 'Ягоды',
        pricePerUnit: 5000,
        visualKey: 'blueberry',
        available: true,
      },
      {
        id: 'decor-blueberry',
        name: 'Черника',
        category: 'Ягоды',
        pricePerUnit: 5000,
        visualKey: 'blueberry',
        available: true,
      },
      {
        id: 'decor-raspberry',
        name: 'Малина',
        category: 'Ягоды',
        pricePerUnit: 6000,
        visualKey: 'blueberry',
        available: true,
      },
      {
        id: 'decor-choco-drip',
        name: 'Шоколадные подтёки',
        category: 'Шоколад',
        pricePerUnit: 8000,
        visualKey: 'glaze-choco',
        available: true,
      },
      {
        id: 'decor-choco-figure',
        name: 'Шоколадные фигурки',
        category: 'Шоколад',
        pricePerUnit: 12000,
        visualKey: 'chocolate-choco',
        available: true,
      },
      {
        id: 'decor-topper-star',
        name: 'Топпер «Звезда»',
        category: 'Топперы',
        pricePerUnit: 15000,
        visualKey: 'meringue',
        available: true,
      },
      {
        id: 'decor-topper-heart',
        name: 'Топпер «Сердце»',
        category: 'Топперы',
        pricePerUnit: 15000,
        visualKey: 'chocolate-pink',
        available: true,
      },
      {
        id: 'decor-rose',
        name: 'Роза из крема',
        category: 'Цветы',
        pricePerUnit: 10000,
        visualKey: 'cream',
        available: true,
      },
      {
        id: 'decor-lily',
        name: 'Лилия из мастики',
        category: 'Цветы',
        pricePerUnit: 20000,
        visualKey: 'glaze-cream',
        available: true,
      },
      {
        id: 'decor-figurine',
        name: 'Фигурка из мастики',
        category: 'Фигурки',
        pricePerUnit: 18000,
        visualKey: 'chocolate',
        available: true,
      },
      {
        id: 'decor-candle-gold',
        name: 'Свеча золотая',
        category: 'candle',
        pricePerUnit: 15000,
        visualKey: 'candle',
        available: true,
      },
    ],

    shapes: [
      { id: 'circle', name: 'Круглый', surchargePercent: 0 },
      { id: 'square', name: 'Квадратный', surchargePercent: 10 },
      { id: 'heart', name: 'Сердце', surchargePercent: 15 },
    ],

    tierSurcharges: [
      { tierCount: 1, surcharge: 0 },
      { tierCount: 2, surcharge: 30000 },
      { tierCount: 3, surcharge: 60000 },
    ],

    config: {
      maxDecorations: 20,
      maxInscriptionLength: 50,
      minWeightPerTier: 500,
      maxWeightPerTier: 5000,
      weightStep: 500,
    },
  };
}
